env:
  browser: true
  commonjs: true
  es6: true
  jquery: true
extends:
  - eslint:recommended
globals:
  __dirname: readonly
  Atomics: readonly
  SharedArrayBuffer: readonly
  Plotly: true
  moment: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  space-before-function-paren: ["error", {"anonymous": "always", "named": "never", "asyncArrow": "always"}]
  object-curly-spacing: ["error", "never"]
  no-unused-vars: ["error", { "vars": "all", "args": "none", "ignoreRestSiblings": false }]
